version: '3.6'
services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - BASE_URL=/jelly
    volumes:
      - /var/jellyfin/config:/config
      - /var/jellyfin/cache:/cache
      - /var/shared_volume:/media
    restart: unless-stopped
    ports:
      - 8096:8096
      - 8920:8920
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - WEBUI_PORT=8081
    volumes:
      - /var/qbittorrent/config:/config
      - /var/shared_volume:/downloads
    restart: unless-stopped
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - SERVERURL=akari-gw.ddns.net
    ports:
      - 51820:51820/udp
    volumes:
      - /var/wireguard/config:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - FB_BASEURL=/fbrowser
    ports:
      - 8080:80
    volumes:
      - /var/shared_volume:/srv
      - /var/filebrowser/filebrowser.db:/database.db
      - /var/filebrowser/.filebrowser.json:/.filebrowser.json
